import { App, Service, PortfolioProject, BlogPost, TeamMember, Testimonial, Stat } from "@/types";

export const stats: Stat[] = [
  { value: "50+", label: "Projects Delivered" },
  { value: "30+", label: "Happy Clients" },
  { value: "10+", label: "Apps Published" },
  { value: "5+", label: "Years Experience" },
];

export const services: Service[] = [
  {
    id: "mobile-app-development",
    title: "Mobile App Development",
    description: "Android & iOS applications",
    icon: "📱",
    features: ["Native Android (Kotlin)", "Native iOS (Swift)", "Cross-platform (Flutter)", "App Store & Play Store deployment"],
    cta: "Request Quote",
  },
  {
    id: "web-development",
    title: "Web Development",
    description: "Modern business websites and portals",
    icon: "🌐",
    features: ["Business Websites", "E-commerce", "Corporate Portals", "Landing Pages"],
    cta: "Request Quote",
  },
  {
    id: "web-app-development",
    title: "Web Application Development",
    description: "SaaS, dashboards, enterprise systems",
    icon: "⚙️",
    features: ["SaaS Platforms", "CRM Systems", "ERP Solutions", "Analytics Dashboards"],
    cta: "Request Quote",
  },
  {
    id: "ai-chatbot-development",
    title: "AI & Chatbot Development",
    description: "AI assistants and automation",
    icon: "🤖",
    features: ["ChatGPT Integration", "Customer Support Bots", "AI Agents", "Process Automation"],
    cta: "Request Quote",
  },
  {
    id: "plugin-development",
    title: "Plugin Development",
    description: "WordPress, browser, and custom plugins",
    icon: "🔌",
    features: ["WordPress Plugins", "Browser Extensions", "Custom Integrations", "API Connectors"],
    cta: "Request Quote",
  },
  {
    id: "cybersecurity-services",
    title: "Cybersecurity Services",
    description: "Security assessments and consulting",
    icon: "🛡️",
    features: ["Security Audits", "Penetration Testing", "Secure Coding Review", "Vulnerability Assessment"],
    cta: "Request Quote",
  },
];

export const apps: App[] = [
  {
    id: "taskflow-pro",
    name: "TaskFlow Pro",
    shortDescription: "Advanced project management and task tracking for teams",
    description: "TaskFlow Pro is a comprehensive project management application designed for modern teams. It combines intuitive task tracking with powerful collaboration features, making it easy to manage projects of any scale.",
    category: "Productivity",
    icon: "/icons/taskflow.svg",
    screenshots: ["/screenshots/taskflow-1.png", "/screenshots/taskflow-2.png"],
    version: "2.0.1",
    size: "32MB",
    updatedDate: "2025-03-15",
    downloads: 15230,
    features: ["Kanban Boards", "Gantt Charts", "Time Tracking", "Team Collaboration", "File Sharing", "Calendar Integration"],
    requirements: ["Android 8.0+", "4GB RAM recommended", "100MB free space"],
    changelog: [
      { version: "2.0.1", date: "2025-03-15", changes: ["Fixed notification sync issue", "Improved offline mode", "Minor UI fixes"] },
      { version: "2.0.0", date: "2025-02-20", changes: ["New Kanban board view", "Real-time collaboration", "Dark mode support"] },
    ],
    faq: [
      { question: "Is TaskFlow Pro free?", answer: "TaskFlow Pro offers a free tier with basic features. Premium plans start at $9.99/month." },
      { question: "Can I use it offline?", answer: "Yes, TaskFlow Pro supports offline mode with automatic sync when connected." },
    ],
    safety: { virusScanned: true, secureDownload: true, sha256Hash: "a3f5b8c1d2e4f6a7b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1" },
    rating: 4.5,
    developer: "ResultScale AI",
  },
  {
    id: "securevault",
    name: "SecureVault",
    shortDescription: "Enterprise-grade password manager with biometric security",
    description: "SecureVault is a next-generation password manager that combines military-grade encryption with seamless user experience. Protect your digital identity with biometric authentication and secure sharing.",
    category: "Security",
    icon: "/icons/securevault.svg",
    screenshots: ["/screenshots/securevault-1.png", "/screenshots/securevault-2.png"],
    version: "1.5.0",
    size: "28MB",
    updatedDate: "2025-03-10",
    downloads: 28450,
    features: ["AES-256 Encryption", "Biometric Auth", "Secure Sharing", "Password Generator", "Breach Alerts", "Multi-device Sync"],
    requirements: ["Android 9.0+", "3GB RAM", "50MB free space", "Fingerprint or Face Unlock"],
    changelog: [
      { version: "1.5.0", date: "2025-03-10", changes: ["Added breach monitoring", "Improved sync speed", "New UI design"] },
    ],
    faq: [
      { question: "How secure is SecureVault?", answer: "We use AES-256 encryption with zero-knowledge architecture. Your data is encrypted before leaving your device." },
    ],
    safety: { virusScanned: true, secureDownload: true, sha256Hash: "b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2b4" },
    rating: 4.8,
    developer: "ResultScale AI",
  },
  {
    id: "finwise",
    name: "FinWise",
    shortDescription: "Smart personal finance tracker with AI-powered insights",
    description: "FinWise uses artificial intelligence to help you track expenses, create budgets, and achieve your financial goals. Get personalized insights and recommendations based on your spending patterns.",
    category: "Finance",
    icon: "/icons/finwise.svg",
    screenshots: ["/screenshots/finwise-1.png", "/screenshots/finwise-2.png"],
    version: "3.1.0",
    size: "35MB",
    updatedDate: "2025-03-01",
    downloads: 42100,
    features: ["AI Expense Tracking", "Budget Planning", "Investment Tracking", "Bill Reminders", "Credit Score Monitor", "Reports & Analytics"],
    requirements: ["Android 8.0+", "4GB RAM", "80MB free space"],
    changelog: [
      { version: "3.1.0", date: "2025-03-01", changes: ["AI predictions improved", "New investment tracker", "Bug fixes"] },
    ],
    faq: [
      { question: "Is my financial data safe?", answer: "Yes, all data is encrypted with bank-grade security. We never share your financial information." },
    ],
    safety: { virusScanned: true, secureDownload: true, sha256Hash: "c5d7e9f1a3b5c7d9e1f3a5b7c9d1e3f5a7b9c1d3e5f7a9b1c3d5e7f9a1b3c5" },
    rating: 4.6,
    developer: "ResultScale AI",
  },
  {
    id: "lingoai",
    name: "LingoAI",
    shortDescription: "AI-powered language learning with real-time conversation practice",
    description: "LingoAI revolutionizes language learning by combining AI-powered conversations with structured lessons. Practice speaking with our AI tutor and get instant feedback on pronunciation and grammar.",
    category: "Education",
    icon: "/icons/lingoai.svg",
    screenshots: ["/screenshots/lingoai-1.png", "/screenshots/lingoai-2.png"],
    version: "1.2.0",
    size: "45MB",
    updatedDate: "2025-02-20",
    downloads: 18900,
    features: ["AI Conversation Partner", "Speech Recognition", "Grammar Correction", "Vocabulary Builder", "Progress Tracking", "12 Languages"],
    requirements: ["Android 9.0+", "4GB RAM", "150MB free space", "Microphone access"],
    changelog: [
      { version: "1.2.0", date: "2025-02-20", changes: ["New languages added", "Improved speech recognition", "Offline lessons"] },
    ],
    faq: [
      { question: "How many languages can I learn?", answer: "LingoAI currently supports 12 languages including Spanish, French, German, Japanese, and more." },
    ],
    safety: { virusScanned: true, secureDownload: true, sha256Hash: "d6e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6" },
    rating: 4.4,
    developer: "ResultScale AI",
  },
  {
    id: "aidesigner",
    name: "AIDesigner",
    shortDescription: "Generate stunning designs and graphics using AI",
    description: "AIDesigner harnesses the power of generative AI to help you create professional designs in seconds. From social media graphics to presentations, just describe what you need.",
    category: "AI Tools",
    icon: "/icons/aidesigner.svg",
    screenshots: ["/screenshots/aidesigner-1.png", "/screenshots/aidesigner-2.png"],
    version: "2.0.0",
    size: "40MB",
    updatedDate: "2025-03-05",
    downloads: 32100,
    features: ["Text-to-Image Generation", "Style Transfer", "Background Removal", "Template Library", "Batch Processing", "Export HD"],
    requirements: ["Android 10.0+", "6GB RAM", "200MB free space"],
    changelog: [
      { version: "2.0.0", date: "2025-03-05", changes: ["New AI model - 3x faster", "Vector export support", "Collaboration features"] },
    ],
    faq: [
      { question: "Can I use generated images commercially?", answer: "Yes, all images generated with AIDesigner are royalty-free for commercial use." },
    ],
    safety: { virusScanned: true, secureDownload: true, sha256Hash: "e7f9a1b3c5d7e9f1a3b5c7d9e1f3a5b7c9d1e3f5a7b9c1d3e5f7a9b1c3d5e7" },
    rating: 4.7,
    developer: "ResultScale AI",
  },
  {
    id: "fitpulse",
    name: "FitPulse",
    shortDescription: "AI-driven fitness tracker with personalized workout plans",
    description: "FitPulse is your personal AI fitness coach that creates customized workout plans based on your goals, fitness level, and available equipment. Track progress with detailed analytics.",
    category: "Utilities",
    icon: "/icons/fitpulse.svg",
    screenshots: ["/screenshots/fitpulse-1.png", "/screenshots/fitpulse-2.png"],
    version: "1.8.0",
    size: "30MB",
    updatedDate: "2025-02-28",
    downloads: 25600,
    features: ["AI Workout Plans", "Exercise Library", "Progress Tracking", "Nutrition Log", "Wearable Sync", "Video Demonstrations"],
    requirements: ["Android 8.0+", "3GB RAM", "100MB free space"],
    changelog: [
      { version: "1.8.0", date: "2025-02-28", changes: ["New workout categories", "Improved AI recommendations", "Wear OS support"] },
    ],
    faq: [
      { question: "Does FitPulse work with my smartwatch?", answer: "Yes, FitPulse syncs with Wear OS, Apple Watch, and most fitness trackers." },
    ],
    safety: { virusScanned: true, secureDownload: true, sha256Hash: "f8a0b2c4d6e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8" },
    rating: 4.3,
    developer: "ResultScale AI",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    role: "CTO",
    company: "TechVentures Inc.",
    image: "/avatars/sarah.jpg",
    content: "ResultScale AI delivered a robust SaaS platform that transformed our operations. Their expertise in AI integration and modern architecture is outstanding.",
    rating: 5,
  },
  {
    id: "2",
    name: "Michael Chen",
    role: "Founder",
    company: "StartupLab",
    image: "/avatars/michael.jpg",
    content: "The team at ResultScale built our mobile app from concept to launch. Professional, responsive, and technically excellent. Highly recommended!",
    rating: 5,
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    role: "Product Manager",
    company: "DataFlow Systems",
    image: "/avatars/emily.jpg",
    content: "Their cybersecurity audit was thorough and actionable. They identified vulnerabilities we hadn't considered and helped us implement robust security measures.",
    rating: 5,
  },
  {
    id: "4",
    name: "David Park",
    role: "CEO",
    company: "InnovateTech",
    image: "/avatars/david.jpg",
    content: "Working with ResultScale AI on our AI chatbot was a game-changer. Customer satisfaction scores increased by 40% within the first month.",
    rating: 5,
  },
];

export const portfolioProjects: PortfolioProject[] = [
  {
    id: "1",
    title: "E-Commerce Platform",
    description: "A full-featured e-commerce platform with AI-powered recommendations",
    images: ["/portfolio/ecommerce-1.png", "/portfolio/ecommerce-2.png"],
    features: ["AI Product Recommendations", "Real-time Inventory", "Payment Gateway Integration", "Admin Dashboard"],
    technologies: ["React", "Node.js", "PostgreSQL", "Redis", "AWS"],
    clientIndustry: "Retail",
    results: ["300% increase in sales", "50% faster checkout", "95% customer satisfaction"],
  },
  {
    id: "2",
    title: "Healthcare Management System",
    description: "Comprehensive healthcare management system for clinics and hospitals",
    images: ["/portfolio/healthcare-1.png", "/portfolio/healthcare-2.png"],
    features: ["Patient Records", "Appointment Scheduling", "Telemedicine", "Billing System"],
    technologies: ["Next.js", "NestJS", "PostgreSQL", "Docker", "Cloudflare"],
    clientIndustry: "Healthcare",
    results: ["60% reduction in paperwork", "40% faster appointments", "99.9% uptime"],
  },
  {
    id: "3",
    title: "AI Customer Support Bot",
    description: "Intelligent chatbot handling customer inquiries across multiple channels",
    images: ["/portfolio/chatbot-1.png", "/portfolio/chatbot-2.png"],
    features: ["NLP Understanding", "Multi-channel Support", "Analytics Dashboard", "Human Handoff"],
    technologies: ["Python", "TensorFlow", "FastAPI", "React", "WebSocket"],
    clientIndustry: "Customer Service",
    results: ["80% automated responses", "24/7 availability", "50% cost reduction"],
  },
  {
    id: "4",
    title: "Financial Analytics Dashboard",
    description: "Real-time financial analytics and reporting platform",
    images: ["/portfolio/finance-1.png", "/portfolio/finance-2.png"],
    features: ["Real-time Data", "Interactive Charts", "Automated Reports", "Alert System"],
    technologies: ["React", "D3.js", "Node.js", "TimescaleDB", "AWS"],
    clientIndustry: "Finance",
    results: ["70% faster reporting", "Real-time insights", "Compliance automated"],
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    slug: "future-of-ai-in-mobile-apps",
    title: "The Future of AI in Mobile Applications",
    excerpt: "Explore how artificial intelligence is reshaping mobile app development and user experiences.",
    content: "Artificial intelligence is no longer a futuristic concept - it's here and transforming mobile applications...",
    category: "AI",
    author: "ResultScale AI Team",
    date: "2025-03-10",
    readTime: "5 min read",
    image: "/blog/ai-mobile.jpg",
    tags: ["AI", "Mobile Development", "Machine Learning"],
  },
  {
    id: "2",
    slug: "cybersecurity-best-practices-2025",
    title: "Cybersecurity Best Practices for 2025",
    excerpt: "Stay ahead of threats with these essential cybersecurity practices for your business.",
    content: "In an increasingly digital world, cybersecurity is more critical than ever...",
    category: "Cybersecurity",
    author: "ResultScale AI Team",
    date: "2025-03-05",
    readTime: "7 min read",
    image: "/blog/cybersecurity.jpg",
    tags: ["Cybersecurity", "Security", "Best Practices"],
  },
  {
    id: "3",
    slug: "building-scalable-web-apps-nextjs",
    title: "Building Scalable Web Applications with Next.js",
    excerpt: "Learn how to build high-performance, scalable web applications using Next.js.",
    content: "Next.js has become the go-to framework for building modern web applications...",
    category: "Web Development",
    author: "ResultScale AI Team",
    date: "2025-02-28",
    readTime: "6 min read",
    image: "/blog/nextjs.jpg",
    tags: ["Next.js", "Web Development", "React"],
  },
  {
    id: "4",
    slug: "cross-platform-vs-native-development",
    title: "Cross-Platform vs Native Development: Which to Choose?",
    excerpt: "A comprehensive comparison to help you decide between cross-platform and native app development.",
    content: "Choosing between cross-platform and native development is a critical decision...",
    category: "Mobile Development",
    author: "ResultScale AI Team",
    date: "2025-02-20",
    readTime: "8 min read",
    image: "/blog/cross-platform.jpg",
    tags: ["Mobile Development", "Flutter", "React Native", "Native"],
  },
  {
    id: "5",
    slug: "introduction-to-ai-agents",
    title: "Introduction to AI Agents: What They Are and How to Build Them",
    excerpt: "Discover the world of AI agents and learn how to build intelligent autonomous systems.",
    content: "AI agents represent the next evolution in artificial intelligence...",
    category: "AI",
    author: "ResultScale AI Team",
    date: "2025-02-15",
    readTime: "10 min read",
    image: "/blog/ai-agents.jpg",
    tags: ["AI", "Agents", "Automation"],
  },
  {
    id: "6",
    slug: "software-engineering-trends-2025",
    title: "Top Software Engineering Trends to Watch in 2025",
    excerpt: "Stay ahead of the curve with these key software engineering trends shaping the industry.",
    content: "The software engineering landscape continues to evolve at a rapid pace...",
    category: "Software Engineering",
    author: "ResultScale AI Team",
    date: "2025-02-10",
    readTime: "6 min read",
    image: "/blog/trends.jpg",
    tags: ["Software Engineering", "Trends", "Technology"],
  },
];

export const teamMembers: TeamMember[] = [
  {
    name: "Alex Rivera",
    role: "CEO & Founder",
    image: "/team/alex.jpg",
    bio: "Visionary leader with 15+ years in software development and AI.",
  },
  {
    name: "Dr. Priya Sharma",
    role: "CTO",
    image: "/team/priya.jpg",
    bio: "PhD in Computer Science, specializing in AI and machine learning.",
  },
  {
    name: "James Wilson",
    role: "Head of Engineering",
    image: "/team/james.jpg",
    bio: "Full-stack expert with experience at top tech companies.",
  },
  {
    name: "Lisa Chen",
    role: "Head of Cybersecurity",
    image: "/team/lisa.jpg",
    bio: "Certified ethical hacker and security architecture specialist.",
  },
];

export const categories: { value: string; label: string }[] = [
  { value: "all", label: "All Categories" },
  { value: "Productivity", label: "Productivity" },
  { value: "Business", label: "Business" },
  { value: "Finance", label: "Finance" },
  { value: "Education", label: "Education" },
  { value: "AI Tools", label: "AI Tools" },
  { value: "Security", label: "Security" },
  { value: "Utilities", label: "Utilities" },
  { value: "Entertainment", label: "Entertainment" },
];
